# Site(s) information
# region: region of the world
#   N.B. used to create output folder structure
# sitename: tide gauge name or other site name
#   N.B. if site_name has an apostrophe use triple quotes
#       # sitename: '''site'x'''
# sitelatlon: site location's latitude and longitude
#   N.B. if tide gauge name: latlon taken from TG metadata
        # sitelatlon: [[]])
#   N.B. if other site name: latlon needs to be specified
        # sitelatlon: [[-51.69, -57.82]])
siteinfo:
    region: 'cmip7_example'   # str
    sitename: ['Stanley II']     # list
    sitelatlon: [[]]             # list

# Base output directory
#   N.B. the code will add region to the output directory
experiment_name: 'cmip7_example'
baseoutdir: '/add/your/directory/'

# Set the end year of the projection(s)
projection_end_year: 2300 # int between 2050 and 2300

# Emulator settings
emulator_settings:
    emulator_mode: true # bool
    use_input_ensemble: true # bool
    gmslr_output_dir: '/ProFSea/ProFSea-tool/data/runs/gmslr'
    emulator_scenario: ['high-extension', 'high-overshoot', 'medium-extension', 'medium-overshoot', 'low', 'verylow', 'verylow-overshoot'] # str
    
scm_data:
    temperature: '/results/fair_output/cmip7_temperature.nc' # str
    ocean_heat_content: '/results/fair_output/cmip7_ohc.nc' # str
    cumulative_emissions: '/data/cumulative_cmip7_emissions.json' # str

# Science method
#   UKCP18 --> sciencemethod: 'UK'
#   Palmer et al (2020) --> sciencemethod: 'global
#       N.B. Used to identify which GIA estimates to use
sciencemethod: 'global'  # str

# Tide gauge information (recommend default below)
# source: source of tide gauge information
#   N.B. Also used to identify which TG directory to use
# datafq: temporal scale of tide gauge data
#   N.B. not set up monthly files for PSMSL
# psmsldir: TG base directory
tidegaugeinfo:
    source: 'PSMSL'    # str
    datafq: ['annual'] # list
    psmsldir: '/home/user/data/PSMSL/'

# CMIP information
cmipinfo:
    mip: 'CMIP6'  # str
# cmip_sea: for non-UK locations, specify if site is within marginal sea
#   Not in a marginal sea --> cmip_sea: 'all'
#   Marginal sea --> cmip_sea: 'marginal'
    cmip_sea: 'all'     # str
# sealevelbasedir: Base directory for CMIP "zos" and "zostoga" data
    sealevelbasedir: '/data/cmip6/'
# slopecoeffsuk: CMIP5 slope coefficients developed for UKCP18
    slopecoeffsuk: '/data/uk_cmip_slope_coefficients/'


# Directories for the GIA estimates (independent of scenario)
#   UKCP18 --> UK specific ones
#   Global locations --> Lambeck, ICE5G
giaestimates:
    global: '/data/gia_estimates/global_GIA_interpolators.pickle'
    uk: '‘/data/gia_estimates/Bradley_GIA_interpolator.pickle'

# Directories for the Slangen, Spada and Klemann fingerprints
fingerprints:
    slangendir: '/data/grd_fingerprints/'
    spadadir: '/data/grd_fingerprints/'
    klemanndir: '/data/grd_fingerprints/'

# Directory of Monte Carlo time series for new projections
#   N.B. Originally developed by Jonathan Gregory
short_montecarlodir: '/path/to/2100/montecarlo/simulations' # Required for projections up to 2100
long_montecarlodir: '/data/runs/emulator_output' # Required for projections from 2100 up to 2300
